services:
  - type: web
    name: eventmap-api
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: bash start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
